---
sudo: required
language: python
python:
  - "2.7"
  - "3.6"

services:
  - docker
cache:
  - pip

before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule
  # - pip install required driver (e.g. docker, python-vagrant, shade, boto, apache-libcloud)
  - pip install docker
  - pip install yamllint flake8 ansible-lint
  - pip install testinfra
script:
  - ansible --version
  - molecule --version
  - docker -v
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
