---
# file: tasks/setup_debian.yml
#
# Task file to setup the Percona apt repository.

- name: Add the Percona APT repository to the APT sources
  apt:
    deb: "{{ percona_apt_download_url }}"
    update_cache: "yes"
    cache_valid_time: 3600
